import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

type Language = 'en' | 'rw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Comprehensive translations for Rwandan context
const translations = {
  en: {
    // Navigation & Header
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.signup': 'Get Started',
    'nav.logout': 'Logout',
    'nav.settings': 'Settings',
    'nav.notifications': 'Notifications',
    'nav.createCourse': 'Create Course',
    'nav.myCourses': 'My Courses',
    'nav.progress': 'Progress',
    
    // Landing Page
    'landing.hero.title': 'Learn Digital Skills',
    'landing.hero.subtitle': 'In Kinyarwanda.',
    'landing.hero.description': 'Join thousands of young Rwandans mastering technology skills with courses designed for our community. Learn coding, design, and digital entrepreneurship in your native language.',
    'landing.hero.cta': 'Start Learning Today',
    'landing.hero.demo': 'Watch Demo',
    
    // Landing Page - Featured Course
    'landing.featuredCourse.title': 'Featured Course',
    'landing.featuredCourse.free': 'Free',
    'landing.featuredCourse.webDev.title': 'Introduction to Web Development',
    'landing.featuredCourse.webDev.description': 'Learn the basics of HTML, CSS, and JavaScript to build your first website',
    'landing.featuredCourse.learnMore': 'Learn More',
    'landing.featuredCourse.new': 'New',
    
    // Landing Page - Trust Indicators
    'landing.trust.freeCourses': 'Free courses available',

    'landing.trust.instructors': 'Expert instructors',
    
    // Landing Page - Sample Courses
    'landing.courses.programming.title': 'Introduction to Programming',
    'landing.courses.programming.description': 'Learn the fundamentals of programming with modern languages and best practices.',
    'landing.courses.webDev.title': 'Web Development Basics',
    'landing.courses.webDev.description': 'Build your first website with HTML, CSS, and JavaScript fundamentals.',
    'landing.courses.marketing.title': 'Digital Marketing Fundamentals',
    'landing.courses.marketing.description': 'Learn essential digital marketing strategies for modern businesses.',
    'landing.courses.category.programming': 'Programming',
    'landing.courses.category.webDevelopment': 'Web Development',
    'landing.courses.category.marketing': 'Marketing',
    'landing.courses.instructor.john': 'John Smith',
    'landing.courses.instructor.sarah': 'Sarah Johnson',
    'landing.courses.instructor.mike': 'Mike Davis',
    'landing.courses.viewCourse': 'View Course',
    'landing.courses.viewAll': 'View All Courses',
    'landing.courses.by': 'by',
    
    // Stats
    'stats.learners': 'Young Learners',
    'stats.tutors': 'Community Mentors',
    'stats.courses': 'Courses Available',
    'stats.success': 'Success Rate',
    
    // Features
    'features.title': 'Why Choose Tek Riders?',
    'features.subtitle': 'Experience learning designed specifically for young Rwandans, with content that speaks to your dreams and challenges.',
    'features.learn.title': 'Learn from Community Leaders',
    'features.learn.description': 'Access courses from successful Rwandan entrepreneurs and tech professionals who understand your journey.',
    'features.track.title': 'Track Your Growth',
    'features.track.description': 'Monitor your progress with tools designed to help you build a portfolio that opens doors to opportunities.',
    'features.interactive.title': 'Hands-on Projects',
    'features.interactive.description': 'Work on real projects that solve problems in your community while building valuable skills.',
    'features.community.title': 'Ubuntu Learning',
    'features.community.description': 'Connect with fellow young learners across Rwanda and East Africa in our supportive community.',

    'features.secure.title': 'Secure & Reliable',
    'features.secure.description': 'Your data and progress are protected with secure authentication and reliable infrastructure.',
    'features.global.title': 'Global Access',
    'features.global.description': 'Learn from anywhere in the world with our responsive platform that works on any device.',
    
    // Testimonials
    'testimonials.title': 'Stories from Our Community',
    'testimonials.subtitle': 'Young Rwandans who transformed their lives through digital skills.',
    'testimonial.amara.quote': 'Tek Riders gave me hope when I had none. Learning web development in Kinyarwanda helped me start my own tech business in Kigali.',
    'testimonial.jean.quote': 'From a village in Musanze to working with international clients - Tek Riders made my data science dreams possible. Murakoze cyane!',
    'testimonial.grace.quote': 'As a young woman in tech, finding mentors who understood my culture was everything. Now I design apps used across East Africa.',
    
    // CTA Section
    'cta.title': 'Ready to Change Your Future?',
    'cta.subtitle': 'Join over 5,000 young Rwandans who are building better lives through technology.',
    'cta.start': 'Start Free Today',
    'cta.browse': 'Explore Courses',
    
    // Footer
    'footer.description': 'Empowering young Rwandans worldwide with quality education and innovative learning experiences designed for our community.',
    'footer.platform.title': 'Platform',
    'footer.platform.browseCourses': 'Browse Courses',
    'footer.platform.becomeTutor': 'Become a Mentor',
    'footer.platform.mobileApp': 'Mobile App',
    'footer.support.title': 'Support',
    'footer.support.helpCenter': 'Help Center',
    'footer.support.contactUs': 'Contact Us',
    'footer.support.community': 'Community',
    'footer.company.title': 'Company',
    'footer.company.aboutUs': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.privacy': 'Privacy Policy',
    'footer.copyright': '© 2025 Tek Riders. All rights reserved.',
    
    // Auth Pages
    'auth.welcome': 'Welcome!',
    'auth.welcomeBack': 'Welcome Back!',
    'auth.continueJourney': 'Continue your journey to digital success',
    'auth.joinCommunity': 'Join Our Community',
    'auth.startJourney': 'Begin your path to digital empowerment',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.chooseRole': 'Choose your role:',
    'auth.learner': 'Learner',
    'auth.tutor': 'Tutor',
    'auth.hasAccount': 'Already have an account?',
    'auth.noAccount': 'New to Tek Riders?',
    'auth.createAccount': 'Create your account',
    'auth.signInAccount': 'Sign in to your account',
    'auth.agreeTerms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.freeJoin': 'Free to join',
    'auth.communitySize': '5K+ young learners',
    'auth.expertMentors': 'Community mentors',
    'auth.emailPlaceholder': 'Enter your email address',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.termsText': 'By signing up, you agree to our',
    'auth.termsLink': 'Terms of Service',
    'auth.privacyLink': 'Privacy Policy',
    'auth.and': 'and',
    
    // Dashboard - Common
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Ready to continue building your future? Let\'s pick up where you left off.',
    'dashboard.coursesEnrolled': 'Courses Enrolled',
    'dashboard.hoursLearned': 'Hours Learned',

    'dashboard.streakDays': 'Streak Days',
    'dashboard.continueLearning': 'Continue Learning',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.browseCourses': 'Browse Courses',
    'dashboard.createCourse': 'Share Knowledge',
    'dashboard.joinCommunity': 'Join Community',
    'dashboard.achievements': 'Achievements',
    'dashboard.streakTitle': 'Day Streak!',
    'dashboard.streakMessage': 'You\'re building momentum! Keep growing.',
    'dashboard.keepStreak': 'Keep Learning',

    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Overview of platform statistics and recent activities',
    'admin.dashboard.totalUsers': 'Total Users',
    'admin.dashboard.totalCourses': 'Total Courses',
    'admin.dashboard.activeUsers': 'Active Users',
    'admin.dashboard.totalEnrollments': 'Total Enrollments',
    'admin.dashboard.userManagement': 'User Management',
    'admin.dashboard.userManagementDesc': 'Manage user accounts and permissions',
    'admin.dashboard.courseManagement': 'Course Management',
    'admin.dashboard.courseManagementDesc': 'Review and manage course content',
    'admin.dashboard.admins': 'Admins',
    'admin.dashboard.tutors': 'Tutors',
    'admin.dashboard.learners': 'Learners',
    'admin.dashboard.inactive': 'Inactive',
    'admin.dashboard.published': 'Published',
    'admin.dashboard.pending': 'Pending',
    'admin.dashboard.draft': 'Draft',
    'admin.dashboard.rejected': 'Rejected',
    'admin.dashboard.recentActivities': 'Recent Activities',
    'admin.dashboard.recentActivitiesDesc': 'Latest platform updates and user activities',
    'admin.dashboard.pendingCourseApprovals': 'Pending Course Approvals',
    'admin.dashboard.viewAll': 'View All',
    'admin.dashboard.review': 'Review',
    'admin.dashboard.noRecentActivities': 'No recent activities',
    'admin.dashboard.noPendingApprovals': 'No pending course approvals',
    'admin.dashboard.refreshing': 'Refreshing...',
    'admin.dashboard.refresh': 'Refresh',
    'admin.dashboard.noData': 'No dashboard data available',

    // Admin Courses
    'admin.courses.title': 'Course Management',
    'admin.courses.description': 'Review and manage all platform courses',
    'admin.courses.refresh': 'Refresh',
    'admin.courses.totalCourses': 'Total Courses',
    'admin.courses.published': 'Published',
    'admin.courses.pending': 'Pending',
    'admin.courses.draft': 'Draft',
    'admin.courses.search': 'Search',
    'admin.courses.status': 'Status',
    'admin.courses.category': 'Category',
    'admin.courses.level': 'Level',
    'admin.courses.clearFilters': 'Clear Filters',
    'admin.courses.course': 'Course',
    'admin.courses.instructor': 'Instructor',
    'admin.courses.enrollments': 'Enrollments',
    'admin.courses.rating': 'Rating',
    'admin.courses.created': 'Created',
    'admin.courses.actions': 'Actions',
    'admin.courses.approve': 'Approve',
    'admin.courses.reject': 'Reject',
    'admin.courses.delete': 'Delete',
    'admin.courses.cancel': 'Cancel',
    'admin.courses.approveCourse': 'Approve Course',
    'admin.courses.rejectCourse': 'Reject Course',
    'admin.courses.viewCourse': 'View Course',
    'admin.courses.deleteCourse': 'Delete Course',
    'admin.courses.approveModal.title': 'Approve Course',
    'admin.courses.approveModal.message': 'Are you sure you want to approve',
    'admin.courses.approveModal.feedback': 'Feedback (optional)',
    'admin.courses.approveModal.feedbackPlaceholder': 'Add any feedback for the instructor...',
    'admin.courses.approveModal.cancel': 'Cancel',
    'admin.courses.approveModal.approve': 'Approve Course',
    'admin.courses.rejectModal.title': 'Reject Course',
    'admin.courses.rejectModal.message': 'Are you sure you want to reject',
    'admin.courses.rejectModal.reason': 'Reason for rejection',
    'admin.courses.rejectModal.reasonPlaceholder': 'Please provide a reason for rejection...',
    'admin.courses.rejectModal.reject': 'Reject Course',
    'admin.courses.approveCourseDesc': 'Are you sure you want to approve the course',
    'admin.courses.rejectCourseDesc': 'Are you sure you want to reject the course',
    'admin.courses.approvalFeedbackPlaceholder': 'Add feedback for the instructor (optional)...',
    'admin.courses.rejectionReasonPlaceholder': 'Please provide a reason for rejection...',
    'admin.courses.searchPlaceholder': 'Search courses by title or tutor...',
    'admin.courses.allStatuses': 'All Statuses',
    'admin.courses.allCategories': 'All Categories',
    'admin.courses.allLevels': 'All Levels',
    'admin.courses.tutor': 'Tutor',
    'admin.courses.status.draft': 'Draft',
    'admin.courses.status.pending': 'Pending',
    'admin.courses.status.submitted': 'Under Review',
    'admin.courses.status.approved': 'Approved',
    'admin.courses.status.published': 'Published',
    'admin.courses.status.rejected': 'Rejected',
    'admin.courses.status.archived': 'Archived',
    'admin.courses.stats.total': 'Total',
    'admin.courses.pagination.previous': 'Previous',
    'admin.courses.pagination.next': 'Next',
    'admin.courses.pagination.page': 'Page',
    'admin.courses.pagination.of': 'of',

    // Admin Users
    'admin.users.title': 'User Management',
    'admin.users.description': 'Manage all platform users and their permissions',
    'admin.users.refresh': 'Refresh',
    'admin.users.totalUsers': 'Total Users',
    'admin.users.admins': 'Admins',
    'admin.users.tutors': 'Tutors',
    'admin.users.learners': 'Learners',
    'admin.users.search': 'Search',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.clearFilters': 'Clear Filters',
    'admin.users.user': 'User',
    'admin.users.actions': 'Actions',
    'admin.users.roleManagement': 'Role Management',
    'admin.users.roleWarning': 'Changing user roles affects their permissions. Are you sure?',
    'admin.users.updateRole': 'Update Role',
    'admin.users.searchPlaceholder': 'Search users by name or email...',
    'admin.users.allRoles': 'All Roles',
    'admin.users.allStatuses': 'All Statuses',
    'admin.users.admin': 'Admin',
    'admin.users.tutor': 'Tutor',
    'admin.users.learner': 'Learner',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.suspended': 'Suspended',
    'admin.users.total': 'Total',
    'admin.users.viewDetails': 'View Details',
    'admin.users.activateUser': 'Activate User',
    'admin.users.deactivateUser': 'Deactivate User',
    'admin.users.deleteUser': 'Delete User',
    'admin.users.joined': 'Joined',
    'admin.users.lastLogin': 'Last Login',
    'admin.users.userDetails': 'User Details',
    'admin.users.accountInfo': 'Account Info',
    'admin.users.userId': 'User ID',
    'admin.users.verified': 'Verified',
    'admin.users.learningStats': 'Learning Stats',
    'admin.users.enrolledCourses': 'Enrolled Courses',
    'admin.users.completedCourses': 'Completed Courses',
    'admin.users.profile': 'Profile',
    'admin.users.bio': 'Bio',
    'admin.users.location': 'Location',
    'admin.users.website': 'Website',
    'admin.users.activate': 'Activate',
    'admin.users.deactivate': 'Deactivate',
    'admin.users.yes': 'Yes',
    'admin.users.no': 'No',

    // Tutor Dashboard
    'tutor.dashboard.title': 'Tutor Dashboard',
    'tutor.dashboard.subtitle': 'Monitor your courses and student progress',
    'tutor.dashboard.welcome': 'Welcome back',
    'tutor.dashboard.createCourse': 'Create Course',
    'tutor.dashboard.allCourses': 'All Courses',
    'tutor.dashboard.totalCourses': 'Total Courses',
    'tutor.dashboard.totalStudents': 'Total Students',
    'tutor.dashboard.avgRating': 'Avg Rating',
    'tutor.dashboard.pendingReview': 'Pending Review',
    'tutor.dashboard.published': 'published',
    'tutor.dashboard.acrossAllCourses': 'Across all courses',
    'tutor.dashboard.outOf': 'Out of 5.0',
    'tutor.dashboard.awaitingApproval': 'Awaiting approval',
    'tutor.dashboard.recentCourses': 'My Recent Courses',
    'tutor.dashboard.recentCoursesDesc': 'Your most recently updated courses',
    'tutor.dashboard.noCourses': 'No courses yet',
    'tutor.dashboard.noCoursesDesc': 'Don\'t worry! Start by creating your first course.',
    'tutor.dashboard.createFirstCourse': 'Create Course',
    'tutor.dashboard.courseTitle': 'Course Title',
    'tutor.dashboard.courseDescription': 'Course Description',
    'tutor.dashboard.category': 'Category',
    'tutor.dashboard.level': 'Level',
    'tutor.dashboard.titlePlaceholder': 'Enter course title',
    'tutor.dashboard.descriptionPlaceholder': 'Enter course description',
    'tutor.dashboard.students': 'students',

    // Tutor Courses
    'tutor.courses.title': 'My Courses',
    'tutor.courses.subtitle': 'Manage your courses and track performance',
    'tutor.courses.searchPlaceholder': 'Search your courses...',
    'tutor.courses.allStatus': 'All Status',
    'tutor.courses.allCategories': 'All Categories',
    'tutor.courses.noCourses': 'No courses',
    'tutor.courses.noCoursesDesc': 'You haven\'t created any courses yet. Start by creating your first course!',
    'tutor.courses.noCoursesFound': 'No courses found',
    'tutor.courses.noCoursesFoundDesc': 'Try adjusting your search or filters to find courses.',
    'tutor.courses.clearFilters': 'Clear Filters',
    'tutor.courses.createFirstCourse': 'Create Your First Course',
    'tutor.courses.gettingStarted': 'Getting Started',
    'tutor.courses.step1': 'Click "Create Course" to get started',
    'tutor.courses.step2': 'Fill in your course details',
    'tutor.courses.step3': 'Submit course for admin approval',
    'tutor.courses.step4': 'Once approved, students can enroll',
    'tutor.courses.view': 'View',
    'tutor.courses.edit': 'Edit',
    'tutor.courses.free': 'Free',
    'tutor.courses.courseDetails': 'Course Details',
    'tutor.courses.close': 'Close',
    'tutor.courses.description': 'Description',
    'tutor.courses.noDescription': 'No description provided.',
    'tutor.courses.generalInfo': 'General Information',
    'tutor.courses.instructor': 'Instructor',
    'tutor.courses.timeline': 'Timeline',
    'tutor.courses.created': 'Created',
    'tutor.courses.lastUpdated': 'Last Updated',
    'tutor.courses.status': 'Status',
    'tutor.courses.nextSteps': 'Next Steps',
    'tutor.courses.step1Complete': 'Complete all course information',
    'tutor.courses.step2AddThumbnail': 'Add a course thumbnail',
    'tutor.courses.step3Submit': 'Submit course for admin review',
    'tutor.courses.courseRejected': 'Course Rejected',
    'tutor.courses.rejectedMessage': 'Your course was rejected. Please review the feedback and make necessary changes before resubmitting.',
    'tutor.courses.courseApproved': 'Course Approved!',
    'tutor.courses.approvedMessage': 'Your course has been approved and is now available for student enrollment.',
    'tutor.courses.viewLiveCourse': 'View Live Course',
    'tutor.courses.editCourse': 'Edit Course',
    'tutor.courses.submitForReview': 'Submit for Review',
    'tutor.courses.rating': 'Rating',
    'tutor.courses.reviews': 'Reviews',
    'tutor.courses.connected': 'Connected',
    'tutor.courses.offline': 'Offline',
    'tutor.courses.deleteCourse': 'Delete Course',
    'tutor.courses.deleteMessage': 'Are you sure you want to delete',
    'tutor.courses.deleteCannotUndo': 'This action cannot be undone.',
    'tutor.courses.delete': 'Delete',
    'tutor.courses.cancel': 'Cancel',
    'tutor.courses.live': 'Live',
    'tutor.courses.pending': 'Pending',
    'tutor.courses.draft': 'Draft',
    'tutor.courses.totalCourses': 'Total Courses',
    'tutor.courses.approvedCourses': 'Approved',
    'tutor.courses.pendingCourses': 'Pending',
    'tutor.courses.draftCourses': 'Draft',
    'tutor.courses.rejectedCourses': 'Rejected',
    'tutor.courses.enrollments': 'Enrollments',
    'tutor.courses.mins': 'mins',

    // Course Status Labels
    'status.draft': 'Draft',
    'status.submitted': 'Under Review',
    'status.pending': 'Pending',
    'status.approved': 'Published',
    'status.published': 'Published',
    'status.rejected': 'Rejected',

    // Course Level Labels
    'level.beginner': 'Beginner',
    'level.intermediate': 'Intermediate',
    'level.advanced': 'Advanced',

    // Course Details Modal
    'tutor.courses.students': 'Students',
    'tutor.courses.liveCourse': 'Live',
    'tutor.courses.draftStatus': 'Draft',
    'tutor.courses.pendingStatus': 'Pending',

    // Course Creation
    'courseCreation.editCourse': 'Edit Course',
    'courseCreation.createNewCourse': 'Create New Course',
    'courseCreation.createEngagingCourse': 'Create an engaging course that meets learners\' expectations',
    'courseCreation.loadingEdit': 'Loading course for editing...',
    'courseCreation.loading': 'Loading...',
    'courseCreation.errorLoadingCourse': 'Error Loading Course',
    'courseCreation.goBack': 'Go Back',
    'courseCreation.tryAgain': 'Try Again',
    'courseCreation.step1.title': 'Course Details',
    'courseCreation.step1.description': 'Basic course information',
    'courseCreation.step2.title': 'Modules',
    'courseCreation.step2.description': 'Course content and quizzes',
    'courseCreation.step3.title': 'Assessment',
    'courseCreation.step3.description': 'Final course assessment',
    'courseCreation.step4.title': 'Review & Submit',
    'courseCreation.step4.description': 'Review and publish course',
    'courseCreation.basicInfo': 'Basic Information',
    'courseCreation.basicInfoDesc': 'Provide essential details about your course',
    'courseCreation.courseTitle': 'Course Title',
    'courseCreation.courseTitlePlaceholder': 'Enter course title',
    'courseCreation.courseDescription': 'Course Description',
    'courseCreation.courseDescPlaceholder': 'Provide a detailed description of your course',
    'courseCreation.courseThumbnail': 'Course Thumbnail',
    'courseCreation.thumbnailDesc': 'Upload an attractive image that represents your course',
    'courseCreation.courseModules': 'Course Modules',
    'courseCreation.modulesDesc': 'Create course modules with videos and quizzes',
    'courseCreation.addModule': 'Add Module',
    'courseCreation.noModules': 'No modules yet',
    'courseCreation.noModulesDesc': 'Start by adding your first course module',
    'courseCreation.moduleTitle': 'Module Title',
    'courseCreation.moduleTitlePlaceholder': 'Enter module title',
    'courseCreation.moduleDescription': 'Description',
    'courseCreation.moduleDescPlaceholder': 'Describe this module',
    'courseCreation.estimatedDuration': 'Estimated Duration (minutes)',
    'courseCreation.youtubeVideo': 'YouTube Video',
    'courseCreation.lectureNotes': 'Lecture Notes (PDF)',
    'courseCreation.lectureNotesDesc': 'Upload PDF lecture notes for students to download',
    'courseCreation.moduleQuiz': 'Module Quiz',
    'courseCreation.quizDesc': 'Create a quiz to assess learning from this module',
    'courseCreation.finalAssessment': 'Final Assessment',
    'courseCreation.finalAssessmentDesc': 'Create a comprehensive final assessment covering all course material',
    'courseCreation.noFinalAssessment': 'No Final Assessment',
    'courseCreation.noAssessmentDesc': 'Create a final assessment to test students\' comprehensive understanding',
    'courseCreation.createFinalAssessment': 'Create Final Assessment',
    'courseCreation.assessmentTitle': 'Assessment Title',
    'courseCreation.assessmentQuestions': 'Assessment Questions',
    'courseCreation.assessmentQuestionsDesc': 'Create comprehensive questions to assess overall course learning',
    'courseCreation.reviewSubmit': 'Review & Submit',
    'courseCreation.reviewSubmitDesc': 'Review your course and submit for approval',
    'courseCreation.courseInfo': 'Course Information',
    'courseCreation.title': 'Title',
    'courseCreation.courseSummary': 'Course Summary',
    'courseCreation.modules': 'Modules',
    'courseCreation.totalDuration': 'Total Duration',
    'courseCreation.quizzes': 'Quizzes',
    'courseCreation.saveAsDraft': 'Save as Draft',
    'courseCreation.submitToAdmin': 'Submit to Admin for Approval',
    'courseCreation.saving': 'Saving...',
    'courseCreation.submitting': 'Submitting...',
    'courseCreation.note': 'Note',
    'courseCreation.noteDesc': 'After submission, your course will appear in your courses page with \'Pending\' status until admin approves it.',
    'courseCreation.previous': 'Previous',
    'courseCreation.next': 'Next',
    'courseCreation.beginner': 'Beginner',
    'courseCreation.intermediate': 'Intermediate',
    'courseCreation.advanced': 'Advanced',
    'courseCreation.programming': 'Programming',
    'courseCreation.design': 'Design',
    'courseCreation.businessTech': 'Business Tech',
    'courseCreation.generalIT': 'General IT',
        'courseCreation.courseSaved': 'Course saved successfully!',
    'courseCreation.courseSubmitted': 'Course submitted for admin approval! It will appear in your courses list with "Pending" status.',

    // Course Marketplace
    'courses.title': 'Explore Courses',
    'courses.subtitle': 'Discover skills that will transform your life and open new opportunities.',
    'courses.search': 'Search courses, mentors, or topics...',
    'courses.filters': 'Filters',
    'courses.allCategories': 'All Categories',
    'courses.programming': 'Programming',
    'courses.design': 'Design',
    'courses.businessTech': 'Business Tech',
    'courses.generalIT': 'General IT',
    'courses.allLevels': 'All Levels',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.showing': 'Showing',
    'courses.results': 'results',
    'courses.for': 'for',
    'courses.enrollNow': 'Enroll Now',
    'courses.preview': 'Preview',
    'courses.bestseller': 'Popular',
    'courses.noResults': 'No courses found',
    'courses.adjustFilters': 'Try adjusting your search criteria or filters',
    
    // Hero Card Content
    'hero.card.title': 'Advanced React Development',
    'hero.card.instructor': 'Sarah Johnson',
    'hero.card.description': 'Master modern React development with hooks, context, and real-world projects.',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.by': 'by',
    'common.free': 'Free',
    'common.premium': 'Premium',
    'common.new': 'New',
    'common.popular': 'Popular',
    'common.recommended': 'Recommended',
    'common.retry': 'Retry',
    'common.pageNotFound': 'Page Not Found',
    'common.pageNotFoundDesc': 'The page you are looking for does not exist.',

    // Learner specific
    'learner.welcomeBack': 'Welcome back',
    'learner.continueJourney': 'Continue your learning journey and achieve your goals',
    'learner.enrolledCourses': 'Enrolled Courses',
    'learner.completed': 'Completed',
    'learner.inProgress': 'In Progress',
    'learner.searchCourses': 'Search courses...',
    'learner.availableCourses': 'Available Courses',
    'learner.courses': 'courses',
    'learner.noCoursesFound': 'No courses found',
    'learner.adjustFilters': 'Try adjusting your search or filter criteria',
    'learner.noCourses': 'No courses are available at the moment',
    'learner.clearFilters': 'Clear Filters',
    'learner.loadingDashboard': 'Loading your learning dashboard...',
    'learner.unableToLoad': 'Unable to load dashboard',
    'learner.myCourses': 'My Courses',
    'learner.trackProgress': 'Track your learning progress and continue your studies',
    'learner.totalCourses': 'Total Courses',
    'learner.loadingCourses': 'Loading your courses...',
    'learner.unableToLoadCourses': 'Unable to load courses',
    'learner.searchYourCourses': 'Search your courses...',
    'learner.enrolledCoursesTitle': 'Your Enrolled Courses',
    'learner.noEnrolledCourses': 'No enrolled courses',
    'learner.noCoursesMatchSearch': 'No courses match your search',
    'learner.startLearningJourney': 'Start your learning journey by enrolling in courses',
    'learner.tryDifferentSearch': 'Try a different search term',
    'learner.browseCourses': 'Browse Courses',
    'learner.clearSearch': 'Clear Search',
    'learner.notStarted': 'Not Started',
    'learner.lessons': 'lessons',
    'learner.currentLesson': 'Current lesson',
    'learner.review': 'Review',
    'learner.continue': 'Continue',

    'quiz.attempts.remaining': 'Attempts remaining',
    'quiz.attempts.unlimited': 'Unlimited attempts',
    'quiz.attempts.none': 'No attempts remaining',
    'quiz.attempts.last': 'Last attempt',
    'quiz.attempts.next': 'Next attempt',
    'quiz.attempts.used': 'Attempts used',
    'quiz.attempts.total': 'Total attempts',
    'quiz.attempts.current': 'Current attempt',
    'quiz.attempts.best': 'Best attempt',
    'quiz.attempts.worst': 'Worst attempt',
    'quiz.attempts.average': 'Average score',
    'quiz.attempts.highest': 'Highest score',
    'quiz.attempts.lowest': 'Lowest score',
    'quiz.attempts.first': 'First attempt',
    'quiz.attempts.second': 'Second attempt',
    'quiz.attempts.third': 'Third attempt',
    'quiz.attempts.fourth': 'Fourth attempt',
    'quiz.attempts.fifth': 'Fifth attempt',

    // Gamification
    'gamification.achievements': 'Achievements',
    'gamification.points': 'points',
    'gamification.level': 'Level',
    'gamification.modules': 'Modules',
    'gamification.quizzes': 'Quizzes',
    'gamification.perfect': 'Perfect',
    'gamification.days': 'Days',
    'gamification.badges': 'Badges',
    'gamification.pts': 'pts',
            'gamification.completeModules': 'Complete modules and quizzes to earn badges!',
        'gamification.loading': 'Loading achievements...',
        
        // Notifications
        'notifications.title': 'Notifications',
        'notifications.noNotifications': 'No notifications yet',
        'notifications.markAllRead': 'Mark all read',
        'notifications.loadMore': 'Load more',
        'notifications.total': 'Total',
        'notifications.unread': 'Unread',
        'notifications.markAsRead': 'Mark as read',
        'notifications.delete': 'Delete',
        'notifications.priority': {
          'low': 'Low',
          'medium': 'Medium',
          'high': 'High',
          'urgent': 'Urgent'
        },
        'notifications.types': {
          'course_enrollment': 'Course Enrollment',
          'course_completion': 'Course Completion',
          'achievement_unlocked': 'Achievement Unlocked',
          'assignment_reminder': 'Assignment Reminder',
          'course_announcement': 'Course Announcement',
          'grade_posted': 'Grade Posted',
          'maintenance_notice': 'Maintenance Notice',
          'welcome_email': 'Welcome'
        },

    // Analytics Dashboard
    'analytics.dashboard': 'Analytics Dashboard',
    'analytics.platformPerformance': 'Platform performance and insights',
    'analytics.errorLoading': 'Error Loading Analytics',
    'analytics.noData': 'No Analytics Data',
    'analytics.dataNotAvailable': 'Analytics data is not available.',
    'analytics.retry': 'Retry',
    'analytics.sevenDays': '7 Days',
    'analytics.thirtyDays': '30 Days',
    'analytics.ninetyDays': '90 Days',
    'analytics.totalUsers': 'Total Users',
    'analytics.totalCourses': 'Total Courses',
    'analytics.totalEnrollments': 'Total Enrollments',
    'analytics.activeUsers': 'Active Users',
    'analytics.published': 'published',
    'analytics.completionRate': 'completion rate',
    'analytics.lastSevenDays': 'Last 7 days',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.userDistribution': 'User Distribution',
    'analytics.learners': 'Learners',
    'analytics.tutors': 'Tutors',
    'analytics.admins': 'Admins',
    'analytics.inactiveUsers': 'Inactive Users',
    'analytics.topPerformingCourses': 'Top Performing Courses',
    'analytics.by': 'by',
    'analytics.enrollments': 'enrollments',
    'analytics.completion': 'completion',
    'analytics.enrollmentTrends': 'Enrollment Trends',
    'analytics.newUsers': 'New Users',
    'analytics.newCourses': 'New Courses',
    'analytics.newEnrollments': 'New Enrollments',
    'analytics.courseCompletions': 'Course Completions',
    'analytics.lastThirtyDays': 'Last 30 days',
    'analytics.users': 'Users',
    'analytics.courses': 'Courses',
    'analytics.completions': 'Completions'
  },
  rw: {
    // Navigation & Header
    'nav.home': 'Ahabanza',
    'nav.courses': 'Amasomo',
    'nav.dashboard': 'Ikibaho',
    'nav.profile': 'Umwirondoro',
    'nav.login': 'Kwinjira',
    'nav.signup': 'Tangira',
    'nav.logout': 'Gusohoka',
    'nav.settings': 'Igenamiterere',
    'nav.notifications': 'Amakuru',
    'nav.createCourse': 'Kora Isomo',
    'nav.myCourses': 'Amasomo Yanjye',
    'nav.progress': 'Iterambere',
    
    // Landing Page
    'landing.hero.title': 'Iga Ikoranabuhanga Rigezweho',
    'landing.hero.subtitle': 'Mu Kinyarwanda.',
    'landing.hero.description': 'Jya mu rubyiruko rw\'u Rwanda rwiga ubuhanga bwa tekinoroji mu masomo yakozwe ku rubyiruko rwacu. Wige gukora porogaramu, gushushanya, no kwihangana mu bucuruzi bwa digitale mu rurimi rwawe.',
    'landing.hero.cta': 'Tangira Kwiga Uyu Munsi',
    'landing.hero.demo': 'Reba Icyitegererezo',
    
    // Landing Page - Featured Course
    'landing.featuredCourse.title': 'Isomo Rihariwe',
    'landing.featuredCourse.free': 'Ku Ubuntu',
    'landing.featuredCourse.webDev.title': 'Intangiriro yo Gukora Urubuga',
    'landing.featuredCourse.webDev.description': 'Wige ibisanzwe bya HTML, CSS, na JavaScript kugira ngo ukore urubuga rwawe rwa mbere',
    'landing.featuredCourse.learnMore': 'Menya Byinshi',
    'landing.featuredCourse.new': 'Gishya',
    
    // Landing Page - Trust Indicators
    'landing.trust.freeCourses': 'Amasomo y\'ubuntu aboneka',

    'landing.trust.instructors': 'Abarimu b\'ubuhanga',
    
    // Landing Page - Sample Courses
    'landing.courses.programming.title': 'Intangiriro yo Gukora Porogaramu',
    'landing.courses.programming.description': 'Wige ibisanzwe byo gukora porogaramu ukoresheje indimi z\'iki gihe n\'uburyo bwiza.',
    'landing.courses.webDev.title': 'Ibisanzwe byo Gukora Urubuga',
    'landing.courses.webDev.description': 'Kora urubuga rwawe rwa mbere ukoresheje HTML, CSS, na JavaScript.',
    'landing.courses.marketing.title': 'Ibisanzwe by\'Ubwamamaza bwa Digitale',
    'landing.courses.marketing.description': 'Wige uburyo bw\'ibanze bwo kwamamaza mu bucuruzi bw\'iki gihe.',
    'landing.courses.category.programming': 'Gukora Porogaramu',
    'landing.courses.category.webDevelopment': 'Gukora Urubuga',
    'landing.courses.category.marketing': 'Ubwamamaza',
    'landing.courses.instructor.john': 'John Smith',
    'landing.courses.instructor.sarah': 'Sarah Johnson',
    'landing.courses.instructor.mike': 'Mike Davis',
    'landing.courses.viewCourse': 'Reba Isomo',
    'landing.courses.viewAll': 'Reba Amasomo Yose',
    'landing.courses.by': 'na',
    
    // Stats
    'stats.learners': 'Urubyiruko Rwiga',
    'stats.tutors': 'Abarimu b\'Umuryango',
    'stats.courses': 'Amasomo Aboneka',
    'stats.success': 'Igipimo cy\'Intsinzi',
    
    // Features
    'features.title': 'Kuki wahitamo Tek Riders?',
    'features.subtitle': 'Menya uburyo bwo kwiga bwakozwe ku rubyiruko rw\'u Rwanda, hamwe n\'ibirimo bivuga ku nzozi zawe n\'ibibazo byawe.',
    'features.learn.title': 'Wige ku Bayobozi b\'Umuryango',
    'features.learn.description': 'Bona amasomo y\'abacuruzi b\'u Rwanda batsinze n\'abahanga ba tekinoroji bazi urugendo rwawe.',
    'features.track.title': 'Genzura Iterambere Ryawe',
    'features.track.description': 'Koresha ibikoresho byakozwe kugira ngo ugufashe kubaka portfolio ifungura inzira z\'amahirwe.',
    'features.interactive.title': 'Vuba & Bifatika',
    'features.interactive.description': 'Kora ku mishinga ifatika n\'ibirimo bifatika byakozwe ku buryo bwo kwiga bw\'iki gihe.',
    'features.community.title': 'Kwiga Ubuntu',
    'features.community.description': 'Huza n\'urubyiruko rundi rwiga mu Rwanda no mu Burasirazuba bw\'Afurika mu muryango wacu ushyigikira.',

    'features.secure.title': 'Umutekano & Kwizera',
    'features.secure.description': 'Amakuru yawe n\'iterambere byarindiriwe n\'ubwishingizi bw\'umutekano n\'uburyo bwizewe.',
    'features.global.title': 'Kwinjira ku Isi Yose',
    'features.global.description': 'Wiga uhereye aho aho hose ku isi ukoresheje urubuga rwacu rwumvikana rukora kuri buri gikoresho.',
    
    // Testimonials
    'testimonials.title': 'Inkuru z\'Umuryango Wacu',
    'testimonials.subtitle': 'Urubyiruko rw\'u Rwanda rwahinduye ubuzima bwarwo binyuze mu buhanga bwa digitale.',
    'testimonial.amara.quote': 'Tek Riders yampagarije ibyiringiro igihe ntari mfite na kimwe. Kwiga gukora urubuga mu Kinyarwanda byamfashije gutangira ubucuruzi bwanjye bwa tekinoroji i Kigali.',
    'testimonial.jean.quote': 'Kuva mu cyaro cya Musanze kugeza ku gukora n\'abakiriya mpuzamahanga - Tek Riders yakoze inzozi zanjye z\'ubumenyi bw\'amakuru zishoboka. Murakoze cyane!',
    'testimonial.grace.quote': 'Nk\'umukobwa mukuru mu buhanga, kubona abayobozi babyumva umuco wanjye byari byose. Ubu nkora porogaramu zikoreshwa mu Burasirazuba bw\'Afurika.',
    
    // CTA Section
    'cta.title': 'Witeguye Guhindura Ejo Hazaza Hawe?',
    'cta.subtitle': 'Jya mu rubyiruko rw\'u Rwanda rurenga 5,000 rubaka ubuzima bwiza binyuze mu buhanga.',
    'cta.start': 'Tangira Uyu Munsi',
    'cta.browse': 'Shakisha Amasomo',
    
    // Footer
    'footer.description': 'Gushimangira urubyiruko rw\'u Rwanda rw\'isi yose n\'uburezi bwiza n\'uburambe bwo kwiga bushya bwakozwe ku muryango wacu.',
    'footer.platform.title': 'Urubuga',
    'footer.platform.browseCourses': 'Shakisha Amasomo',
    'footer.platform.becomeTutor': 'Ba Umwarimu',
    'footer.platform.mobileApp': 'Porogaramu yo muri Telefoni',
    'footer.support.title': 'Umutwe',
    'footer.support.helpCenter': 'Umwanya w\'Ubufasha',
    'footer.support.contactUs': 'Duhamagare',
    'footer.support.community': 'Umuryango',
    'footer.company.title': 'Ikigo',
    'footer.company.aboutUs': 'Turi bande',
    'footer.company.careers': 'Akazi',
    'footer.company.privacy': 'Politiki y\'Amahame',
    'footer.copyright': '© 2025 Tek Riders. Uburenganzira bwose burarinzwe.',
    
    // Auth Pages
    'auth.welcome': 'Murakaza neza!',
    'auth.welcomeBack': 'Murakaza neza!',
    'auth.continueJourney': 'Komeza urugendo rwawe rwo gutsinda mu buhanga',
    'auth.joinCommunity': 'Injira mu Muryango',
    'auth.startJourney': 'Tangira urugendo rwo gushimangira ubuhanga',
    'auth.email': 'Email',
    'auth.password': 'Ijambo banga',
    'auth.confirmPassword': 'Emeza Ijambo banga',
    'auth.fullName': 'Amazina Yose',
    'auth.rememberMe': 'Nyibuka',
    'auth.forgotPassword': 'Wibagiwe ijambo banga?',
    'auth.signIn': 'Kwinjira',
    'auth.signUp': 'Kora Konti',
    'auth.chooseRole': 'Hitamo uruhare rwawe:',
    'auth.learner': 'Umunyeshuri',
    'auth.tutor': 'Umwarimu',
    'auth.hasAccount': 'Usanzwe ufite konti?',
    'auth.noAccount': 'Uri mushya kuri Tek Riders?',
    'auth.createAccount': 'Kora konti yawe',
    'auth.signInAccount': 'Injira muri konti yawe',
    'auth.agreeTerms': 'Nemeye amabwiriza yo gukoresha na politiki y\'ubwoba',
    'auth.freeJoin': 'Ubuntu kwinjira',
    'auth.communitySize': '5K+ urubyiruko rwiga',
    'auth.expertMentors': 'Abayobozi b\'umuryango',
    'auth.emailPlaceholder': 'Andika aderesi ya email yawe',
    'auth.passwordPlaceholder': 'Andika ijambo banga',
    'auth.confirmPasswordPlaceholder': 'Emeza ijambo banga',
    'auth.fullNamePlaceholder': 'Andika amazina yawe yose',
    'auth.signingIn': 'Birimo kwinjira...',
    'auth.creatingAccount': 'Irimo gufunguka...',
    'auth.termsText': 'Mu kwiyandikisha, wemera',
    'auth.termsLink': 'Terms of Service',
    'auth.privacyLink': 'Privacy Policy',
    'auth.and': 'na',
    
    // Dashboard - Common
    'dashboard.welcome': 'Murakaza neza',
    'dashboard.subtitle': 'Witeguye gukomeza kubaka ejo hazaza hawe? Reka dukomeze aho twari.',
    'dashboard.coursesEnrolled': 'Amasomo Wanditsemo',
    'dashboard.hoursLearned': 'Amasaha Wize',

    'dashboard.streakDays': 'Iminsi Ikurikirana',
    'dashboard.continueLearning': 'Komeza Kwiga',
    'dashboard.quickActions': 'Ibikorwa Byihuse',
    'dashboard.browseCourses': 'Shakisha Amasomo',
    'dashboard.createCourse': 'Shyiraho Isomo',
    'dashboard.joinCommunity': 'Injira mu Muryango',
    'dashboard.achievements': 'Ibyagezweho',
    'dashboard.streakTitle': 'Iminsi Ikurikirana!',
    'dashboard.streakMessage': 'Urimo kubaka ibigwi! Komereza aho.',
    'dashboard.keepStreak': 'Komeza Kwiga',

    // Admin Dashboard
    'admin.dashboard.title': 'Ikibaho cy\'Umuyobozi',
    'admin.dashboard.subtitle': 'Incamake y\'imibare y\'urubuga n\'ibikorwa bya nyuma',
    'admin.dashboard.totalUsers': 'Abakoresha Bose',
    'admin.dashboard.totalCourses': 'Amasomo Yose',
    'admin.dashboard.activeUsers': 'Abakoresha Bakora',
    'admin.dashboard.totalEnrollments': 'Kwiyandikisha Kwose',
    'admin.dashboard.userManagement': 'Gucunga Abakoresha',
    'admin.dashboard.userManagementDesc': 'Gucunga konti z\'abakoresha n\'uburenganzira',
    'admin.dashboard.courseManagement': 'Gucunga Amasomo',
    'admin.dashboard.courseManagementDesc': 'Gusuzuma no gucunga ibirimo by\'amasomo',
    'admin.dashboard.admins': 'Abayobozi',
    'admin.dashboard.tutors': 'Abarimu',
    'admin.dashboard.learners': 'Abanyeshuri',
    'admin.dashboard.inactive': 'Badakora',
    'admin.dashboard.published': 'Byatangajwe',
    'admin.dashboard.pending': 'Bitegereje',
    'admin.dashboard.draft': 'Igishushanyo',
    'admin.dashboard.rejected': 'Byanze',
    'admin.dashboard.recentActivities': 'Ibikorwa bya Nyuma',
    'admin.dashboard.recentActivitiesDesc': 'Amakuru mashya y\'urubuga n\'ibikorwa by\'abakoresha',
    'admin.dashboard.pendingCourseApprovals': 'Amasomo Ategereje Kwemezwa',
    'admin.dashboard.viewAll': 'Reba Yose',
    'admin.dashboard.review': 'Suzuma',
    'admin.dashboard.noRecentActivities': 'Nta bikorwa bya nyuma',
    'admin.dashboard.noPendingApprovals': 'Nta masomo ategereje kwemezwa',
    'admin.dashboard.refreshing': 'Birimo gushyirwa mu buryo...',
    'admin.dashboard.refresh': 'Shyira mu buryo',
    'admin.dashboard.noData': 'Nta makuru y\'ikibaho aboneka',

    // Admin Courses
    'admin.courses.title': 'Gucunga Amasomo',
    'admin.courses.description': 'Suzuma ugacunge amasomo yose y\'urubuga',
    'admin.courses.refresh': 'Shyira mu buryo',
    'admin.courses.totalCourses': 'Amasomo Yose',
    'admin.courses.published': 'Byatangajwe',
    'admin.courses.pending': 'Bitegereje',
    'admin.courses.draft': 'Igishushanyo',
    'admin.courses.search': 'Shakisha',
    'admin.courses.status': 'Uburyo',
    'admin.courses.category': 'Icyiciro',
    'admin.courses.level': 'Urwego',
    'admin.courses.clearFilters': 'Siba Ibishishikira',
    'admin.courses.course': 'Isomo',
    'admin.courses.instructor': 'Umwarimu',
    'admin.courses.enrollments': 'Ibiyandikisho',
    'admin.courses.rating': 'Amanota',
    'admin.courses.created': 'Byakozwe',
    'admin.courses.actions': 'Ibikorwa',
    'admin.courses.approve': 'Emeza',
    'admin.courses.reject': 'Anga',
    'admin.courses.delete': 'Siba',
    'admin.courses.cancel': 'Kuraguza',
    'admin.courses.approveCourse': 'Emeza Isomo',
    'admin.courses.rejectCourse': 'Anga Isomo',
    'admin.courses.viewCourse': 'Reba Isomo',
    'admin.courses.deleteCourse': 'Siba Isomo',
    'admin.courses.approveModal.title': 'Emeza Isomo',
    'admin.courses.approveModal.message': 'Wizeye ko ushaka kwemeza',
    'admin.courses.approveModal.feedback': 'Inyuze (ntabwo byangombwa)',
    'admin.courses.approveModal.feedbackPlaceholder': 'Ongeraho inyuze ku mwarimu...',
    'admin.courses.approveModal.cancel': 'Kuraguza',
    'admin.courses.approveModal.approve': 'Emeza Isomo',
    'admin.courses.rejectModal.title': 'Anga Isomo',
    'admin.courses.rejectModal.message': 'Wizeye ko ushaka kwanga',
    'admin.courses.rejectModal.reason': 'Impamvu yo kwanga',
    'admin.courses.rejectModal.reasonPlaceholder': 'Nyamuneka tanga impamvu yo kwanga...',
    'admin.courses.rejectModal.reject': 'Anga Isomo',
    'admin.courses.approveCourseDesc': 'Wizeye ko ushaka kwemeza isomo',
    'admin.courses.rejectCourseDesc': 'Wizeye ko ushaka kwanga isomo',
    'admin.courses.approvalFeedbackPlaceholder': 'Ongeraho inyuze ku mwarimu (ntabwo byangombwa)...',
    'admin.courses.rejectionReasonPlaceholder': 'Nyamuneka tanga impamvu yo kwanga...',
    'admin.courses.searchPlaceholder': 'Shakisha amasomo ukoresha izina cyangwa umwarimu...',
    'admin.courses.allStatuses': 'Uburyo Bwose',
    'admin.courses.allCategories': 'Ibyiciro Byose',
    'admin.courses.allLevels': 'Amashuri Yose',
    'admin.courses.tutor': 'Umwarimu',
    'admin.courses.status.draft': 'Igishushanyo',
    'admin.courses.status.pending': 'Bitegereje',
    'admin.courses.status.submitted': 'Mu Gusuzuma',
    'admin.courses.status.approved': 'Byemejwe',
    'admin.courses.status.published': 'Byatangajwe',
    'admin.courses.status.rejected': 'Byanze',
    'admin.courses.status.archived': 'Mu bubiko',
    'admin.courses.stats.total': 'Yose',
    'admin.courses.pagination.previous': 'Ibanza',
    'admin.courses.pagination.next': 'Ibikurikira',
    'admin.courses.pagination.page': 'Urupapuro',
    'admin.courses.pagination.of': 'muri',

    // Admin Users
    'admin.users.title': 'Gucunga Abakoresha',
    'admin.users.description': 'Gucunga abakoresha bose b\'urubuga n\'uburenganzira bwabo',
    'admin.users.refresh': 'Shyira mu buryo',
    'admin.users.totalUsers': 'Abakoresha Bose',
    'admin.users.admins': 'Abayobozi',
    'admin.users.tutors': 'Abarimu',
    'admin.users.learners': 'Abanyeshuri',
    'admin.users.search': 'Shakisha',
    'admin.users.role': 'Inshingano',
    'admin.users.status': 'Uburyo',
    'admin.users.clearFilters': 'Siba Ibishishikira',
    'admin.users.user': 'Umukoresha',
    'admin.users.actions': 'Ibikorwa',
    'admin.users.roleManagement': 'Gucunga Inshingano',
    'admin.users.roleWarning': 'Guhindura inshingano z\'umukoresha bigira ingaruka ku burenganzira bwe. Wizeye?',
    'admin.users.updateRole': 'Hindura Inshingano',
    'admin.users.searchPlaceholder': 'Shakisha abakoresha ukoresha amazina cyangwa email...',
    'admin.users.allRoles': 'Inshingano Zose',
    'admin.users.allStatuses': 'Uburyo Bwose',
    'admin.users.admin': 'Umuyobozi',
    'admin.users.tutor': 'Umwarimu',
    'admin.users.learner': 'Umunyeshuri',
    'admin.users.active': 'Bakora',
    'admin.users.inactive': 'Badakora',
    'admin.users.suspended': 'Bahagaritswe',
    'admin.users.total': 'Yose',
    'admin.users.viewDetails': 'Reba Amakuru',
    'admin.users.activateUser': 'Kora Umukoresha',
    'admin.users.deactivateUser': 'Hagarika Umukoresha',
    'admin.users.deleteUser': 'Siba Umukoresha',
    'admin.users.joined': 'Yinjiye',
    'admin.users.lastLogin': 'Ubushize yinjiye',
    'admin.users.userDetails': 'Amakuru y\'Umukoresha',
    'admin.users.accountInfo': 'Amakuru ya Konti',
    'admin.users.userId': 'Indangamuntu y\'Umukoresha',
    'admin.users.verified': 'Byemejwe',
    'admin.users.learningStats': 'Imibare y\'Kwiga',
    'admin.users.enrolledCourses': 'Amasomo Yiyandikishije',
    'admin.users.completedCourses': 'Amasomo Yarangije',
    'admin.users.profile': 'Umwirondoro',
    'admin.users.bio': 'Ubuzima',
    'admin.users.location': 'Aho abarizwa',
    'admin.users.website': 'Urubuga',
    'admin.users.activate': 'Kora',
    'admin.users.deactivate': 'Hagarika',
    'admin.users.yes': 'Yego',
    'admin.users.no': 'Oya',

    // Tutor Dashboard
    'tutor.dashboard.title': 'Ikibaho cy\'Umwarimu',
    'tutor.dashboard.subtitle': 'Koresha amasomo yawe no kugenzura iterambere ry\'abanyeshuri',
    'tutor.dashboard.welcome': 'Murakaza neza',
    'tutor.dashboard.createCourse': 'Kora Isomo',
    'tutor.dashboard.allCourses': 'Amasomo Yose',
    'tutor.dashboard.totalCourses': 'Amasomo Yose',
    'tutor.dashboard.totalStudents': 'Abanyeshuri Bose',
    'tutor.dashboard.avgRating': 'Amanota Rusange',
    'tutor.dashboard.pendingReview': 'Bitegereje Gusuzumwa',
    'tutor.dashboard.published': 'byatangajwe',
    'tutor.dashboard.acrossAllCourses': 'Ku masomo yose',
    'tutor.dashboard.outOf': 'Muri 5.0',
    'tutor.dashboard.awaitingApproval': 'Bitegereje kwemezwa',
    'tutor.dashboard.recentCourses': 'Amasomo Yanjye ya Nyuma',
    'tutor.dashboard.recentCoursesDesc': 'Amasomo yawe yavuguruwe vuba',
    'tutor.dashboard.noCourses': 'Nta masomo',
    'tutor.dashboard.noCoursesDesc': 'Ntugire ubwoba! Tangira ukore isomo ryawe rya mbere.',
    'tutor.dashboard.createFirstCourse': 'Kora Isomo',
    'tutor.dashboard.courseTitle': 'Izina ry\'Isomo',
    'tutor.dashboard.courseDescription': 'Ibisobanuro by\'Isomo',
    'tutor.dashboard.category': 'Icyiciro',
    'tutor.dashboard.level': 'Urwego',
    'tutor.dashboard.titlePlaceholder': 'Andika izina ry\'isomo',
    'tutor.dashboard.descriptionPlaceholder': 'Andika ibisobanuro by\'isomo',
    'tutor.dashboard.students': 'abanyeshuri',

    // Tutor Courses
    'tutor.courses.title': 'Amasomo Yanjye',
    'tutor.courses.subtitle': 'Gucunga amasomo yawe no gukurikirana imikorere',
    'tutor.courses.searchPlaceholder': 'Shakisha amasomo yawe...',
    'tutor.courses.allStatus': 'Uburyo Bwose',
    'tutor.courses.allCategories': 'Ibyiciro Byose',
    'tutor.courses.noCourses': 'Nta masomo',
    'tutor.courses.noCoursesDesc': 'Nturakora amasomo. Tangira ukore isomo ryawe rya mbere!',
    'tutor.courses.noCoursesFound': 'Nta masomo aboneka',
    'tutor.courses.noCoursesFoundDesc': 'Gerageza guhindura inyandiko cyangwa akayunguruzo.',
    'tutor.courses.clearFilters': 'Siba Akayunguruzo',
    'tutor.courses.createFirstCourse': 'Kora Isomo Ryawe Rya Mbere',
    'tutor.courses.gettingStarted': 'Gutangira',
    'tutor.courses.step1': 'Kanda "Kora Isomo" kugira ngo utangire',
    'tutor.courses.step2': 'Uzuza amakuru y\'isomo ryawe',
    'tutor.courses.step3': 'Ohereza isomo kugira ngo ryemezwe',
    'tutor.courses.step4': 'Nyuma y\'uko ryemejwe, abanyeshuri bashobora kwiyandikisha',
    'tutor.courses.view': 'Reba',
    'tutor.courses.edit': 'Hindura',
    'tutor.courses.free': 'Ku Ubuntu',
    'tutor.courses.courseDetails': 'Amakuru y\'Isomo',
    'tutor.courses.close': 'Funga',
    'tutor.courses.description': 'Ibisobanuro',
    'tutor.courses.noDescription': 'Nta bisobanuro byatanzwe.',
    'tutor.courses.generalInfo': 'Amakuru Rusange',
    'tutor.courses.instructor': 'Umwarimu',
    'tutor.courses.timeline': 'Igihe',
    'tutor.courses.created': 'Byakozwe',
    'tutor.courses.lastUpdated': 'Byavuguruwe',
    'tutor.courses.status': 'Uburyo',
    'tutor.courses.nextSteps': 'Ibikurikira',
    'tutor.courses.step1Complete': 'Uzuza amakuru yose y\'isomo',
    'tutor.courses.step2AddThumbnail': 'Ongeramo ifoto y\'isomo',
    'tutor.courses.step3Submit': 'Ohereze isomo kugira ngo ryemezwe',
    'tutor.courses.courseRejected': 'Isomo Ryanze',
    'tutor.courses.rejectedMessage': 'Isomo ryawe ryanze. Reba inyuze ugakosora ibyo bimaze osubize isomo.',
    'tutor.courses.courseApproved': 'Isomo Ryemejwe!',
    'tutor.courses.approvedMessage': 'Isomo ryawe ryemejwe kandi abanyeshuri bashobora kwiyandikisha.',
    'tutor.courses.viewLiveCourse': 'Reba Isomo ku Rubuga',
    'tutor.courses.editCourse': 'Hindura Isomo',
    'tutor.courses.submitForReview': 'Ohereza Gusuzumwa',
    'tutor.courses.rating': 'Amanota',
    'tutor.courses.reviews': 'Ibiciro',
    'tutor.courses.connected': 'Byunganiye',
    'tutor.courses.offline': 'Bidahuriwe',
    'tutor.courses.deleteCourse': 'Siba Isomo',
    'tutor.courses.deleteMessage': 'Wizeye ko ushaka gusiba',
    'tutor.courses.deleteCannotUndo': 'Ibi ntibihinduka.',
    'tutor.courses.delete': 'Siba',
    'tutor.courses.cancel': 'Reka',
    'tutor.courses.live': 'Byatangajwe',
    'tutor.courses.pending': 'Bitegereje',
    'tutor.courses.draft': 'Igishushanyo',
    'tutor.courses.totalCourses': 'Amasomo Yose',
    'tutor.courses.approvedCourses': 'Byemejwe',
    'tutor.courses.pendingCourses': 'Bitegereje',
    'tutor.courses.draftCourses': 'Igishushanyo',
    'tutor.courses.rejectedCourses': 'Byanze',
    'tutor.courses.enrollments': 'Abanyeshuri',
    'tutor.courses.mins': 'min',

    // Course Status Labels
    'status.draft': 'Igishushanyo',
    'status.submitted': 'Bitegereye',
    'status.pending': 'Bitegereje',
    'status.approved': 'Byemejwe',
    'status.published': 'Byatangajwe',
    'status.rejected': 'Byanze',

    // Course Level Labels
    'level.beginner': 'Rwintangiriro',
    'level.intermediate': 'Rwagaciro',
    'level.advanced': 'Rwimbere',

    // Course Details Modal
    'tutor.courses.students': 'Abanyeshuri',
    'tutor.courses.liveCourse': 'Byatangajwe',
    'tutor.courses.draftStatus': 'Igishushanyo',
    'tutor.courses.pendingStatus': 'Bitegereje',

    // Course Creation
    'courseCreation.editCourse': 'Hindura Isomo',
    'courseCreation.createNewCourse': 'Kora Isomo Rishya',
    'courseCreation.createEngagingCourse': 'Kora isomo ryiza rirebana n\'ibyizerezo by\'abanyeshuri',
    'courseCreation.loadingEdit': 'Turimo gufungura isomo...',
    'courseCreation.loading': 'Turimo gukora...',
    'courseCreation.errorLoadingCourse': 'Ikosa Ry\'aho Gufungura Isomo',
    'courseCreation.goBack': 'Garuka',
    'courseCreation.tryAgain': 'Ongera Ugerageze',
    'courseCreation.step1.title': 'Amakuru y\'Isomo',
    'courseCreation.step1.description': 'Amakuru y\'ibanze ku isomo',
    'courseCreation.step2.title': 'Ibice',
    'courseCreation.step2.description': 'Ibirimo by\'isomo n\'ibizamini',
    'courseCreation.step3.title': 'Ikizamini',
    'courseCreation.step3.description': 'Ikizamini cya nyuma',
    'courseCreation.step4.title': 'Gusuzuma no Kohereza',
    'courseCreation.step4.description': 'Suzuma ugaherezahe isomo',
    'courseCreation.basicInfo': 'Amakuru y\'Ibanze',
    'courseCreation.basicInfoDesc': 'Tanga amakuru y\'ibanze ku isomo ryawe',
    'courseCreation.courseTitle': 'Izina ry\'Isomo',
    'courseCreation.courseTitlePlaceholder': 'Andika izina ry\'isomo',
    'courseCreation.courseDescription': 'Ibisobanuro by\'Isomo',
    'courseCreation.courseDescPlaceholder': 'Sobanura isomo ryawe mu buryo bwambitse',
    'courseCreation.courseThumbnail': 'Ishusho y\'Isomo',
    'courseCreation.thumbnailDesc': 'Shyiramo ishusho nziza izakorwa kugaragaza isomo ryawe',
    'courseCreation.courseModules': 'Ibice by\'Isomo',
    'courseCreation.modulesDesc': 'Kora ibice by\'isomo hamwe n\'amashusho n\'ibizamini',
    'courseCreation.addModule': 'Ongeraho Igice',
    'courseCreation.noModules': 'Nta bice',
    'courseCreation.noModulesDesc': 'Tangira wongere igice cya mbere cy\'isomo ryawe',
    'courseCreation.moduleTitle': 'Izina ry\'Igice',
    'courseCreation.moduleTitlePlaceholder': 'Andika izina ry\'igice',
    'courseCreation.moduleDescription': 'Ibisobanuro',
    'courseCreation.moduleDescPlaceholder': 'Sobanura iki gice',
    'courseCreation.estimatedDuration': 'Igihe Giteganijwe (mu minota)',
    'courseCreation.youtubeVideo': 'Amashusho ya YouTube',
    'courseCreation.lectureNotes': 'Inyandiko z\'Isomo (PDF)',
    'courseCreation.lectureNotesDesc': 'Shyiramo inyandiko z\'isomo za PDF kugira ngo abanyeshuri bazifashe',
    'courseCreation.moduleQuiz': 'Ikizamini cy\'Igice',
    'courseCreation.quizDesc': 'Kora ikizamini gisuzuma ibyigishijwe muri iki gice',
    'courseCreation.finalAssessment': 'Ikizamini cya Nyuma',
    'courseCreation.finalAssessmentDesc': 'Kora ikizamini cya nyuma gisuzuma byose byigishijwe mu isomo',
    'courseCreation.noFinalAssessment': 'Nta kizamini cya nyuma',
    'courseCreation.noAssessmentDesc': 'Kora ikizamini cya nyuma gisuzuma ubumenyi bwose bw\'abanyeshuri',
    'courseCreation.createFinalAssessment': 'Kora Ikizamini cya Nyuma',
    'courseCreation.assessmentTitle': 'Izina ry\'Ikizamini',
    'courseCreation.assessmentQuestions': 'Ibibazo by\'Ikizamini',
    'courseCreation.assessmentQuestionsDesc': 'Kora ibibazo byiza bisuzuma ubumenyi bwose bw\'isomo',
    'courseCreation.reviewSubmit': 'Gusuzuma no Kohereza',
    'courseCreation.reviewSubmitDesc': 'Suzuma isomo ryawe hanyuma ushyikirize',
    'courseCreation.courseInfo': 'Amakuru y\'Isomo',
    'courseCreation.title': 'Izina',
    'courseCreation.courseSummary': 'Incamake',
    'courseCreation.modules': 'Ibice',
    'courseCreation.totalDuration': 'Igihe Cyose',
    'courseCreation.quizzes': 'Ibizamini',
    'courseCreation.saveAsDraft': 'Bika Nk\'Urutonde',
    'courseCreation.submitToAdmin': 'Ohereza Umuyobozi Gusuzuma',
    'courseCreation.saving': 'Urabika...',
    'courseCreation.submitting': 'Urohereza...',
    'courseCreation.note': 'Icyitonderwa',
    'courseCreation.noteDesc': 'Nyuma yo kohereza, isomo ryawe rizagaragara mu masomo yawe rikaba "Bitegereje" kugeza umuyobozi aryemeje.',
    'courseCreation.previous': 'Ibanza',
    'courseCreation.next': 'Ibikurikira',
    'courseCreation.beginner': 'Umutagira ubumenyi',
    'courseCreation.intermediate': 'Uzi bike',
    'courseCreation.advanced': 'Umunyamuzi',
    'courseCreation.programming': 'Porogaramu',
    'courseCreation.design': 'Gushushanya',
    'courseCreation.businessTech': 'Ikoranabuhanga mu Bucuruzi',
    'courseCreation.generalIT': 'Ikoranabuhanga Rusange',
        'courseCreation.courseSaved': 'Isomo ryakingwa neza!',
    'courseCreation.courseSubmitted': 'Isomo ryawe ryohererejwe kugira ngo ryemezwe! Rizagaragara mu masomo yawe rikaba "Bitegereje".',

    // Course Marketplace
    'courses.title': 'Shakisha Amasomo',
    'courses.subtitle': 'Menya ubuhanga buzahindura ubuzima bwawe kandi bufnafungure amahirwe mashya.',
    'courses.search': 'Shakisha amasomo, abarimu, cyangwa ingingo...',
    'courses.filters': 'Amashyushyu',
    'courses.allCategories': 'Ibyiciro Byose',
    'courses.programming': 'Porogaramu',
    'courses.design': 'Igishushanyo',
    'courses.businessTech': 'Tekinoroji y\'Ubucuruzi',
    'courses.generalIT': 'Tekinoroji Rusange',
    'courses.allLevels': 'Urwego Rwose',
    'courses.beginner': 'Utangira',
    'courses.intermediate': 'Hagati',
    'courses.advanced': 'Urwego rwo Hejuru',
    'courses.showing': 'Werekana',
    'courses.results': 'ibisubizo',
    'courses.for': 'kuri',
    'courses.enrollNow': 'Iyandikishe Ubu',
    'courses.preview': 'Reba Mbere',
    'courses.bestseller': 'Gikunda',
    'courses.noResults': 'Nta masomo aboneka',
    'courses.adjustFilters': 'Gerageza guhindura ibisabwa byawe byo gushakisha cyangwa amashyushyu',
    
    // Hero Card Content
    'hero.card.title': 'Iterambere mu React',
    'hero.card.instructor': 'Sarah Johnson',
    'hero.card.description': 'Wiga gutera imbere mu React ukoresheje hooks, context, n\'imishinga nyayo.',
    
    // Common
    'common.loading': 'Birimo gutegurwa...',
    'common.save': 'Bika',
    'common.cancel': 'Reka',
    'common.continue': 'Komeza',
    'common.back': 'Subira inyuma',
    'common.next': 'Ibikurikira',
    'common.previous': 'Ibyabanje',
    'common.close': 'Funga',
    'common.viewAll': 'Reba Byose',
    'common.learnMore': 'Menya Byinshi',
    'common.getStarted': 'Tangira',
    'common.by': 'Na',
    'common.free': 'Ku Ubuntu',
    'common.premium': 'Kirenze',
    'common.new': 'Gishya',
    'common.popular': 'Kizwi cyane',
    'common.recommended': 'Byasabwe',
    'common.retry': 'Ongera ugerageze',
    'common.pageNotFound': 'Urupapuro Rutaboneka',
    'common.pageNotFoundDesc': 'Urupapuro ushakisha ntiruhari.',

    // Learner specific
    'learner.welcomeBack': 'Murakaza neza',
    'learner.continueJourney': 'Komeza urugendo rwawe rwo kwiga ugere ku ntego zawe',
    'learner.enrolledCourses': 'Amasomo Wanditsemo',
    'learner.completed': 'Byarangiye',
    'learner.inProgress': 'Birimo kukorwa',
    'learner.searchCourses': 'Shakisha amasomo...',
    'learner.availableCourses': 'Amasomo Aboneka',
    'learner.courses': 'amasomo',
    'learner.noCoursesFound': 'Nta masomo aboneka',
    'learner.adjustFilters': 'Gerageza guhindura inyandiko cyangwa akayunguruzo',
    'learner.noCourses': 'Nta masomo aboneka ubu',
    'learner.clearFilters': 'Siba Akayunguruzo',
    'learner.loadingDashboard': 'Turimo gufungura ikibaho cyawe...',
    'learner.unableToLoad': 'Bidashoboka gufungura ikibaho',
    'learner.myCourses': 'Amasomo Yanjye',
    'learner.trackProgress': 'Koresha iterambere ryawe ugakomeze kwiga',
    'learner.totalCourses': 'Amasomo Yose',
    'learner.loadingCourses': 'Turimo gufungura amasomo yawe...',
    'learner.unableToLoadCourses': 'Bidashoboka gufungura amasomo',
    'learner.searchYourCourses': 'Shakisha amasomo yawe...',
    'learner.enrolledCoursesTitle': 'Amasomo Wanditsemo',
    'learner.noEnrolledCourses': 'Nta masomo wanditsemo',
    'learner.noCoursesMatchSearch': 'Nta masomo ahuje n\'inyandiko yawe',
    'learner.startLearningJourney': 'Tangira urugendo rwawe rwo kwiga unyuze mu kwiyandikisha mu masomo',
    'learner.tryDifferentSearch': 'Gerageza ijambo rishya',
    'learner.browseCourses': 'Shakisha Amasomo',
    'learner.clearSearch': 'Siba Inyandiko',
    'learner.notStarted': 'Ntabwo Byatangiye',
    'learner.lessons': 'amasomo',
    'learner.currentLesson': 'Isomo rya ubu',
    'learner.review': 'Subiramo',
    'learner.continue': 'Komeza',

    'quiz.attempts.remaining': 'Attempts remaining',
    'quiz.attempts.unlimited': 'Unlimited attempts',
    'quiz.attempts.none': 'No attempts remaining',
    'quiz.attempts.last': 'Last attempt',
    'quiz.attempts.next': 'Next attempt',
    'quiz.attempts.used': 'Attempts used',
    'quiz.attempts.total': 'Total attempts',
    'quiz.attempts.current': 'Current attempt',
    'quiz.attempts.best': 'Best attempt',
    'quiz.attempts.worst': 'Worst attempt',
    'quiz.attempts.average': 'Average score',
    'quiz.attempts.highest': 'Highest score',
    'quiz.attempts.lowest': 'Lowest score',
    'quiz.attempts.first': 'First attempt',
    'quiz.attempts.second': 'Second attempt',
    'quiz.attempts.third': 'Third attempt',
    'quiz.attempts.fourth': 'Fourth attempt',
    'quiz.attempts.fifth': 'Fifth attempt',

    // Gamification
    'gamification.achievements': 'Ibihembo',
    'gamification.points': 'amagambo',
    'gamification.level': 'Urupapuro',
    'gamification.modules': 'Amasomo',
    'gamification.quizzes': 'Amazamini',
    'gamification.perfect': 'Amagambo yuzuye',
    'gamification.days': 'Umunsi',
    'gamification.badges': 'Ibimenyetso',
    'gamification.pts': 'amagambo',
            'gamification.completeModules': 'Gerageza amasomo kugira ngo ubone ibimenyetso!',
        'gamification.loading': 'Turimo gushaka...',
        
        // Notifications
        'notifications.title': 'Ubutumwa',
        'notifications.noNotifications': 'Nta butumwa buhari',
        'notifications.markAllRead': 'Bika byose bisomwe',
        'notifications.loadMore': 'Bika byinshi',
        'notifications.total': 'Byose',
        'notifications.unread': 'Bitasomwe',
        'notifications.markAsRead': 'Bika bisomwe',
        'notifications.delete': 'Siba',
        'notifications.priority': {
          'low': 'Hasi',
          'medium': 'Hagati',
          'high': 'Hejuru',
          'urgent': 'Byihuse'
        },
        'notifications.types': {
          'course_enrollment': 'Kwiyandikisha kuri isomo',
          'course_completion': 'Kurangiza isomo',
          'achievement_unlocked': 'Ibihembo byemewe',
          'assignment_reminder': 'Ibyifuzo byibutse',
          'course_announcement': 'Amatangazo y\'isomo',
          'grade_posted': 'Amagambo yashyizwe',
          'maintenance_notice': 'Ibutumwa rya serivisi',
          'welcome_email': 'Murakaza neza'
        },

    // Analytics Dashboard
    'analytics.dashboard': 'Ikibaho cy\'Ibipimo',
    'analytics.platformPerformance': 'Imikorere y\'ububiko n\'ubumenyi',
    'analytics.errorLoading': 'Ikosa mu Gufungura Ibipimo',
    'analytics.noData': 'Nta Bipimo Bihari',
    'analytics.dataNotAvailable': 'Ibipimo ntibiboneka.',
    'analytics.retry': 'Ongera ugerageze',
    'analytics.sevenDays': 'Iminsi 7',
    'analytics.thirtyDays': 'Iminsi 30',
    'analytics.ninetyDays': 'Iminsi 90',
    'analytics.totalUsers': 'Abakoresha Bose',
    'analytics.totalCourses': 'Amasomo Yose',
    'analytics.totalEnrollments': 'Kwiyandikisha Kwose',
    'analytics.activeUsers': 'Abakoresha Bakora',
    'analytics.published': 'byatangazwa',
    'analytics.completionRate': 'igipimo cyo kurangiza',
    'analytics.lastSevenDays': 'Iminsi 7 ishize',
    'analytics.recentActivity': 'Ibikorwa By\'Ubu',
    'analytics.userDistribution': 'Gusambura Abakoresha',
    'analytics.learners': 'Abanyeshuri',
    'analytics.tutors': 'Abarimu',
    'analytics.admins': 'Abayobozi',
    'analytics.inactiveUsers': 'Abakoresha Badakora',
    'analytics.topPerformingCourses': 'Amasomo Akora Neza',
    'analytics.by': 'na',
    'analytics.enrollments': 'kwiyandikisha',
    'analytics.completion': 'kurangiza',
    'analytics.enrollmentTrends': 'Imikorere y\'Kwiyandikisha',
    'analytics.newUsers': 'Abakoresha Basha',
    'analytics.newCourses': 'Amasomo Asha',
    'analytics.newEnrollments': 'Kwiyandikisha Gusha',
    'analytics.courseCompletions': 'Kurangiza Amasomo',
    'analytics.lastThirtyDays': 'Iminsi 30 ishize',
    'analytics.users': 'Abakoresha',
    'analytics.courses': 'Amasomo',
    'analytics.completions': 'Kurangiza'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      try {
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'rw')) {
          return savedLanguage;
        }
      } catch (error) {
        console.warn('Failed to load language from localStorage:', error);
      }
    }
    return 'rw'; // Default to Kinyarwanda
  });

  const [isLoading, setIsLoading] = useState(false);

  // Save language to localStorage
  const saveLanguage = useCallback((newLanguage: Language) => {
    try {
      localStorage.setItem('language', newLanguage);
    } catch (error) {
      console.warn('Failed to save language to localStorage:', error);
    }
  }, []);

  // Save language when it changes
  useEffect(() => {
    saveLanguage(language);
  }, [language, saveLanguage]);

  // Enhanced translation function with better error handling
  const t = useCallback((key: string): string => {
    try {
      const translation = translations[language][key as keyof typeof translations['en']];
      if (translation && typeof translation === 'string') {
        return translation;
      }
      
      // Fallback to English if translation not found in current language
      if (language !== 'en') {
        const englishTranslation = translations['en'][key as keyof typeof translations['en']];
        if (englishTranslation && typeof englishTranslation === 'string') {
          console.warn(`Translation missing for key "${key}" in ${language}, falling back to English`);
          return englishTranslation;
        }
      }
      
      // Return the key if no translation found
      console.warn(`Translation missing for key "${key}" in both ${language} and English`);
      return key;
    } catch (error) {
      console.error('Translation error:', error);
      return key;
    }
  }, [language]);

  // Memoized setLanguage function
  const setLanguage = useCallback((newLanguage: Language) => {
    if (newLanguage === 'en' || newLanguage === 'rw') {
      setIsLoading(true);
      setLanguageState(newLanguage);
      // Small delay to ensure smooth transition
      setTimeout(() => setIsLoading(false), 100);
    } else {
      console.warn('Invalid language:', newLanguage);
    }
  }, []);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
    isLoading
  }), [language, setLanguage, t, isLoading]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};